import type { Metadata } from "next";
import { Bellefair } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/NavBar";

const bellefair = Bellefair({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${bellefair.className}`}>
        <div
          className="bg-[url('/home/background-home-mobile.jpg')]
      sm:bg-[url('/home/background-home-tablet.jpg')]
      lg:bg-[url('/home/background-home-desktop.jpg')]
      bg-cover h-screen"
        >
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
