import type { Metadata } from "next";
import { Bellefair } from "next/font/google";
import "./globals.css";

const bellefair = Bellefair({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${bellefair.className}`}>{children}</body>
    </html>
  );
}
